---
title: "Online Retail Transaction Analytics"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
---

```{r setup, include=FALSE}
library(shiny)
library(highcharter)
library(tidyverse)

options(scipen = 999)

# download.file(
#   "http://archive.ics.uci.edu/ml/machine-learning-databases/00352/Online%20Retail.xlsx",
#   "data.xlsx"
# )

dataset = readxl::read_excel("data.xlsx") %>%
  janitor::clean_names()

# cleansing
clean = dataset %>%
  filter(
    !is.na(customerid),
    quantity > 0,
    unitprice > 0,
    str_length(stockcode) >= 5,
    str_length(stockcode) < 12
  ) %>%
  mutate(total_spend = quantity * unitprice)

# identify valuable items
pareto = clean %>%
  select(stockcode, total_spend) %>%
  group_by(stockcode) %>%
  summarise(total_spend = sum(total_spend)) %>%
  ungroup() %>%
  arrange(desc(total_spend)) %>%
  mutate(
    running_trx = cumsum(total_spend),
    running_trx_prop = running_trx / sum(total_spend),
    class = case_when(
      running_trx_prop <= 0.8 ~ "A",
      running_trx_prop <= 1 ~ "B"
    )
  ) %>%
  select(stockcode, class)

# valuable items
class_a = pareto %>%
  filter(class == "A") %>%
  left_join(clean, by = "stockcode") %>%
  select(stockcode, description, invoicedate, quantity, country)

# functions
get_trx_wday_vs_hour_heatmap = function(desc) {
  df = class_a %>%
    filter(description == desc) %>%
    mutate(
      wday = lubridate::wday(invoicedate, label = T),
      hour = lubridate::hour(invoicedate)
    ) %>%
    group_by(wday, hour) %>%
    summarise(quantity = sum(quantity)) %>%
    complete(wday, hour = full_seq(0:23, 1), fill = list(quantity = 0))

  tooltip <- JS(
    "function(){",
    "return 'Quantity: ' + this.point.value;",
    "}"
  )

  df %>%
    hchart("heatmap", hcaes(x = hour, y = wday, value = quantity)) %>%
    hc_xAxis(
      title = list(text = "Hour"),
      tickInterval = 2
    ) %>%
    hc_yAxis(
      title = list(text = "")
    ) %>%
    hc_tooltip(formatter = tooltip) %>%
    hc_legend(enabled = F)
}

get_trx_history_chart = function(desc) {
  df = class_a %>%
    filter(description == desc) %>%
    transmute(
      stockcode,
      invoicedate = invoicedate %>%
        str_sub(1, 10) %>%
        lubridate::ymd(),
      quantity
    ) %>%
    group_by(invoicedate) %>%
    summarise(quantity = sum(quantity)) %>%
    complete(invoicedate = full_seq(invoicedate, 1), fill = list(quantity = 0)) %>%
    rename(date = invoicedate)

  tooltip <- JS(
    "function(){",
    "return '<b>' + this.point.date + '</b>' + '<br>' + 'Quantity: ' + this.point.quantity;",
    "}"
  )

  df %>%
    hchart("spline", hcaes(x = date, y = quantity)) %>%
    hc_yAxis(title = "") %>%
    hc_xAxis(title = "") %>%
    hc_tooltip(formatter = tooltip) %>%
    hc_plotOptions(
      spline = list(marker = list(enabled = F))
    ) %>%
    hc_add_theme(
      hc_theme_google()
    )  %>%
    hc_chart(
      zoomType = "x"
    )
}

get_trx_by_country_chart = function(desc) {
  df = class_a %>%
    filter(description == desc, country != "United Kingdom") %>%
    select(country, quantity) %>%
    group_by(country) %>%
    summarise(quantity = sum(quantity)) %>%
    arrange(desc(quantity)) %>%
    head(5)

  df %>%
    hchart(
      "bar",
      hcaes(x = country, y = quantity)
    ) %>%
    hc_yAxis(
      title = ""
    ) %>%
    hc_xAxis(title = "") %>%
    hc_tooltip(
      pointFormat = "Quantity: {point.quantity}"
    ) %>%
    hc_add_theme(hc_theme_google())
}
```

Sidebar {.sidebar data-width=330}
-------------------------------------

Analysis on purchased items from UK-based and registered non-store online retail. All transactions on this analysis occur between 01/12/2010 and 09/12/2011. For more information about the dataset for this analysis, please have a look at [this link](http://archive.ics.uci.edu/ml/datasets/online+retail). 

Items available are limited using [80/20 rule](https://en.wikipedia.org/wiki/Pareto_principle). More detail about how to do it in **R**, have a look at source code provided.

---

```{r inputs}
selectInput(
  "product_desc", 
  label = tags$b("Select an item to analyze:"), 
  choices = unique(class_a$description), 
  selected = "WHITE HANGING HEART T-LIGHT HOLDER",
  selectize = TRUE,
  width = "100%"
)
```
    
Row {data-height=500}
-------------------------------------

### Transaction History

```{r history_chart}
renderHighchart({get_trx_history_chart(input$product_desc)})
```

Row {data-height=500}
-------------------------------------
   
### Transaction Heatmap

```{r wday_vs_hour_heatmap}
renderHighchart({get_trx_wday_vs_hour_heatmap(input$product_desc)})
```   
    
### Top 5 Non-UK Country Purchased this Item

```{r top_5_country}
renderHighchart({get_trx_by_country_chart(input$product_desc)})
```
